id: P004336
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:12:18.264818
source_metadata:
  id: bdr:W1KG23738
  title: བློ་བཟང་དགོངས་རྒྱན་མུ་ཏིག་ཕྲེང་མཛེས་དེབ་བཅུ་གཉིས་པ།
  author: ''
  volumes:
    7a3955cea11648e6b74def159d96f170:
      image_group_id: I1KG24023
      title: ''
      volume_number: 1
      total_pages: 406
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
